/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! `apkdmverity` is a program that protects a signed APK file using dm-verity. The APK is assumed
//! to be signed using APK signature scheme V4. The idsig file generated by the signing scheme is
//! also used as an input to provide the merkle tree. This program is currently intended to be used
//! to securely mount the APK inside Microdroid. Since the APK is physically stored in the file
//! system managed by the host Android which is assumed to be compromisable, it is important to
//! keep the integrity of the file "inside" Microdroid.
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

mod dm;
mod loopdevice;
mod util;

use anyhow::{anyhow, bail, Context, Result};
use clap::{App, Arg};
use std::fmt::Debug;
use std::fs;
use std::os::unix::fs::FileTypeExt;
use std::path::{Path, PathBuf};

fn main() -> Result<()> {
    let matches = App::new("device_mapper")
        .about(
            "--blkdevice /dev/something creates the blk_device
            --rm_mapping name will remove the device mapping /dev/block/mapper/name",
        )
        .arg(Arg::from_usage(
            "--blkdevice... <device_path> \
                            'Whatever.",
        ))
        .arg(Arg::with_name("rm_mapping").long("rm_mapping").takes_value(true))
        .get_matches();
    if matches.is_present("rm_mapping") {
        // This is far from ideal, very hacky!
        remove_mapping(matches.value_of("rm_mapping").unwrap()).unwrap();
        return Ok(());
    }
    let blkdevice = matches.value_of("blkdevice").unwrap();
    let ret = enable_crypt(blkdevice, "cryptDev")?;
    println!("{:?}", ret);
    Ok(())
}

struct CryptResult {
    data_device: PathBuf,
    hash_device: PathBuf,
    mapper_device: PathBuf,
}

const BLOCK_SIZE: u64 = 4096;
fn remove_mapping(name: &str) -> Result<()> {
    let dm = dm::DeviceMapper::new()?;
    dm.delete_device_deferred(name).unwrap();
    Ok(())
}

fn enable_crypt<P: AsRef<Path> + Debug>(blk_dev: P, name: &str) -> Result<PathBuf> {
    let (data_device, dev_size) = if fs::metadata(&blk_dev)?.file_type().is_block_device() {
        (blk_dev.as_ref().to_path_buf(), util::blkgetsize64(blk_dev.as_ref())?)
    } else {
        // Can we afford to have storage on a loopback device if the backing blk device doesn't exist ?
        println!("the passed blk_dev is not a block device");
        (blk_dev.as_ref().to_path_buf(), 0)
    };
    // Create the dm-crypt spec
    let target = dm::DmCryptTargetBuilder::default()
        .data_device(&data_device, dev_size)
        .build()
        .context("Couldn't build the dmCrypt target. Idk why")?;

    let dm = dm::DeviceMapper::new()?;
    let mapper_device =
        dm.create_crypt_device(name, &target).context("Failed to create dm-crypt device")?;
    Ok(mapper_device)
}
