// Copyright 2023, The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Validates devices in device tree.
//! Declared in separated libs for adding unit tests with libstd.

#[cfg(not(test))]
use alloc::ffi::CString;
#[cfg(not(test))]
use alloc::format;
use core::ffi::CStr;
use libfdt::{Fdt, FdtError, OwnedFdt};
use log::error;
#[cfg(test)]
use std::ffi::CString;

// List of top level nodes generated by crosvm
// Workaround Clippy bug that doesn't detect unsafe comment in global variables.
#[allow(clippy::undocumented_unsafe_blocks)]
// SAFETY: Test ensures nul-terminating. Note that safe version can't be used for constant.
const CROSVM_NODES: &[&CStr] = unsafe {
    &[
        CStr::from_bytes_with_nul_unchecked(b"U6_16550A@2e8\0"),
        CStr::from_bytes_with_nul_unchecked(b"U6_16550A@2f8\0"),
        CStr::from_bytes_with_nul_unchecked(b"U6_16550A@3e8\0"),
        CStr::from_bytes_with_nul_unchecked(b"U6_16550A@3f8\0"),
        CStr::from_bytes_with_nul_unchecked(b"__symbols__\0"),
        CStr::from_bytes_with_nul_unchecked(b"chosen\0"),
        CStr::from_bytes_with_nul_unchecked(b"config\0"),
        CStr::from_bytes_with_nul_unchecked(b"cpufreq\0"),
        CStr::from_bytes_with_nul_unchecked(b"cpus\0"),
        CStr::from_bytes_with_nul_unchecked(b"intc\0"),
        CStr::from_bytes_with_nul_unchecked(b"memory\0"),
        CStr::from_bytes_with_nul_unchecked(b"pci\0"),
        CStr::from_bytes_with_nul_unchecked(b"pclk@3M\0"),
        CStr::from_bytes_with_nul_unchecked(b"pmu\0"),
        CStr::from_bytes_with_nul_unchecked(b"psci\0"),
        CStr::from_bytes_with_nul_unchecked(b"reserved-memory\0"),
        CStr::from_bytes_with_nul_unchecked(b"rtc@2000\0"),
        CStr::from_bytes_with_nul_unchecked(b"timer\0"),
        CStr::from_bytes_with_nul_unchecked(b"vmwdt@3000\0"),
    ]
};

/// Validate devices in the FDT.
///
/// Here's validation criteria:
///   - All root's subnodes must exist in either NODES or VM DTBO.
pub fn validate_devices(fdt: &mut Fdt, vm_dtbo: Option<&[u8]>) -> Result<(), FdtError> {
    let vm_dtb = OwnedFdt::from_overlay_onto_new_fdt(vm_dtbo).map_err(|e| {
        error!("Failed to build VM DTB for validation: {e}");
        e
    })?;
    let vm_dtb_fdt = vm_dtb.as_fdt();

    let fdt_root = fdt.root().map_err(|e| {
        error!("Failed to obtain DT root: {e}");
        e
    })?;
    fdt_root
        .subnodes()
        .map_err(|e| {
            error!("Failed to obtain subnodes of root: {e}");
            e
        })?
        .try_for_each(|node| {
            let name = node.name().map_err(|e| {
                error!("Failed to get subnode's name: {e}");
                e
            })?;
            if CROSVM_NODES.contains(&name) {
                return Ok(());
            }

            let path =
                CString::from_vec_with_nul([b"/", name.to_bytes_with_nul()].concat()).unwrap();
            let node = vm_dtb_fdt.node(&path).map_err(|e| {
                error!("Failed to query node from VM DTBO: {e}");
                e
            })?;
            if node.is_none() {
                error!("Unknown node {name:?} exists in FDT");
                return Err(FdtError::NotFound);
            }

            // TODO(jaewan): Also validate props
            Ok(())
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn vm_dtbo() -> Vec<u8> {
        fs::read("test_pvmfw_vm_dtbo.dtbo").unwrap()
    }

    #[test]
    fn test_crosvm_nodes_name() {
        CROSVM_NODES
            .iter()
            .for_each(|node| assert!(CStr::from_bytes_with_nul(node.to_bytes_with_nul()).is_ok()));
    }

    #[test]
    fn test_validate_devices_without_unknown_devices_nor_vm_dtbo_passes() {
        let mut dtb = fs::read("test_pvmfw_with_defaults.dtb").unwrap();
        let fdt = Fdt::from_mut_slice(dtb.as_mut_slice()).unwrap();
        assert!(validate_devices(fdt, None).is_ok());
    }

    #[test]
    fn test_validate_devices_without_unknown_devices_passes() {
        let mut dtb = fs::read("test_pvmfw_without_unknown_device.dtb").unwrap();
        let fdt = Fdt::from_mut_slice(dtb.as_mut_slice()).unwrap();
        assert!(validate_devices(fdt, Some(vm_dtbo().as_mut_slice())).is_ok());
    }

    #[test]
    fn test_validate_devices_with_unknown_devices_fails() {
        let mut dtb = fs::read("test_pvmfw_with_unknown_device.dtb").unwrap();
        let fdt = Fdt::from_mut_slice(dtb.as_mut_slice()).unwrap();
        assert!(validate_devices(fdt, Some(vm_dtbo().as_mut_slice())).is_err());
    }
}
