; CDDL for the CSR sent from the client VM to the RKP VM for pVM remote attestation.

CsrPayload = [                    ; CBOR Array defining the payload for CSR
   challenge: bstr .size (0..64), ; The challenge is provided by the client server.
                                  ; It will be included in the certificate chain in the
                                  ; attestation result, serving as proof of the freshness
                                  ; of the result.
   PublicKey,                     ; COSE_Key encoded EC P-256 public key [ RFC9053 s7.1.1 ]
                                  ; to be attested. See keymint/PublicKey.cddl for the
                                  ; definition.
]

Csr = [
    DiceCertChain,      ; The DICE chain containing measurement of the client VM. See
                        ; keymint/generateCertificateRequestV2.cddl for the DiceCertChain
                        ; definition.
    SignedData,
]

; COSE_Sign [RFC9052 s4.1]
SignedData = [
    protected: {},            ; The signing algorithms are specified in each signature
                              ; separately.
    unprotected: {},
    payload: CsrPayload,
    Signatures<CsrPayload>,
]

Signatures<Data> = [
    dice_cdi_leaf_signature: COSE_Signature_Dice_Cdi_Leaf<Data>,
    attestation_key_signature: COSE_Signature_Attestation_Key<Data>,
]

; COSE_Signature [RFC9052 s4.1]
COSE_Signature_Dice_Cdi_Leaf<Data> = [
    protected: bstr .cbor { 1: AlgorithmEdDSA },
    unprotected: {},
    signature: bstr,                         ; Ed25519(CDI_Leaf_Priv, SigStruct<Data>)
]

; COSE_Signature [RFC9052 s4.1]
COSE_Signature_Attestation_Key<Data> = [
    protected: bstr .cbor { 1: AlgorithmES256 },
    unprotected: {},
    signature: bstr,                         ; ECDSA(PrivateKey, SigStruct<Data>)
]

; Sig_structure for SignedData [ RFC9052 s4.4 ]
SigStruct<Data> = {
    context: "Signature",
    external_aad: bstr .size 0,
    payload: bstr .cbor Data, ; payload is always filled CsrPayload for this CSR
}

; DER-encoded EC P-256 ECPrivateKey [ RFC 5915 s3 ]
PrivateKey = COSE_Key
