/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.compos.test;

import android.platform.test.annotations.RootPermissionTest;

import static com.android.microdroid.test.CommandResultSubject.assertThat;
import static com.android.microdroid.test.CommandResultSubject.command_results;
import static com.android.tradefed.testtype.DeviceJUnit4ClassRunner.TestLogData;
import static com.android.tradefed.testtype.DeviceJUnit4ClassRunner.TestMetrics;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth.assertWithMessage;

import com.android.microdroid.test.CommandRunner;
import com.android.microdroid.test.MicrodroidHostTestCaseBase;
import com.android.tradefed.device.DeviceNotAvailableException;
import com.android.tradefed.log.LogUtil.CLog;
import com.android.tradefed.result.FileInputStreamSource;
import com.android.tradefed.result.LogDataType;
import com.android.tradefed.testtype.DeviceJUnit4ClassRunner;
import com.android.tradefed.util.CommandResult;
import com.android.tradefed.util.RunUtil;

import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@RootPermissionTest
@RunWith(DeviceJUnit4ClassRunner.class)
public final class ComposTestCase extends MicrodroidHostTestCaseBase {

    // Binaries used in test. (These paths are valid both in host and Microdroid.)
    private static final String ODREFRESH_BIN = "/apex/com.android.art/bin/odrefresh";
    private static final String COMPOSD_CMD_BIN = "/apex/com.android.compos/bin/composd_cmd";
    private static final String COMPOS_VERIFY_BIN =
            "/apex/com.android.compos/bin/compos_verify";

    private static final String COMPOS_APEXDATA_DIR = "/data/misc/apexdata/com.android.compos";

    /** Output directory of odrefresh */
    private static final String TEST_ARTIFACTS_DIR = "test-artifacts";

    private static final String ODREFRESH_OUTPUT_DIR =
            "/data/misc/apexdata/com.android.art/" + TEST_ARTIFACTS_DIR;

    /** Timeout of odrefresh to finish */
    private static final int ODREFRESH_TIMEOUT_MS = 10 * 60 * 1000; // 10 minutes

    // ExitCode expanded from art/odrefresh/include/odrefresh/odrefresh.h.
    private static final int OKAY = 0;
    private static final int COMPILATION_SUCCESS = 80;

    // Files that define the "test" instance of CompOS
    private static final String COMPOS_TEST_ROOT = "/data/misc/apexdata/com.android.compos/test/";

    private static final String SYSTEM_SERVER_COMPILER_FILTER_PROP_NAME =
            "dalvik.vm.systemservercompilerfilter";
    private String mBackupSystemServerCompilerFilter;

    /** Boot time test related variables */
    private static final String BOOT_COMPLETED_PROP = "getprop sys.boot_completed";
    private static final int BOOT_COMPLETE_POLL_INTERVAL = 1000;
    private static final int BOOT_COMPLETE_POLL_RETRY_COUNT = 45;
    private static final String BOOT_COMPLETED_VAL = "1";
    private static final double NANOS_IN_SEC = 1_000_000_000.0;
    private static final int ROUND_COUNT = 2;
    private static final String METRIC_PREFIX = "avf_perf/compos/";

    @Rule public TestLogData mTestLogs = new TestLogData();
    @Rule public TestName mTestName = new TestName();

    @Before
    public void setUp() throws Exception {
        testIfDeviceIsCapable(getDevice());

        String value = getDevice().getProperty(SYSTEM_SERVER_COMPILER_FILTER_PROP_NAME);
        if (value == null) {
            mBackupSystemServerCompilerFilter = "";
        } else {
            mBackupSystemServerCompilerFilter = value;
        }
    }

    @After
    public void tearDown() throws Exception {
        killVmAndReconnectAdb();

        archiveLogThenDelete(mTestLogs, getDevice(), COMPOS_APEXDATA_DIR + "/vm_console.log",
                "vm_console.log-" + mTestName.getMethodName());
        archiveLogThenDelete(mTestLogs, getDevice(), COMPOS_APEXDATA_DIR + "/vm.log",
                "vm.log-" + mTestName.getMethodName());

        CommandRunner android = new CommandRunner(getDevice());

        // Clear up any CompOS instance files we created
        android.tryRun("rm", "-rf", COMPOS_TEST_ROOT);

        // And any artifacts generated by odrefresh
        android.tryRun("rm", "-rf", ODREFRESH_OUTPUT_DIR);

        if (mBackupSystemServerCompilerFilter != null) {
            CLog.d("Restore dalvik.vm.systemservercompilerfilter to "
                    + mBackupSystemServerCompilerFilter);
            getDevice().setProperty(SYSTEM_SERVER_COMPILER_FILTER_PROP_NAME,
                    mBackupSystemServerCompilerFilter);
        }
    }

    @Test
    public void testOdrefreshSpeed() throws Exception {
        getDevice().setProperty(SYSTEM_SERVER_COMPILER_FILTER_PROP_NAME, "speed");
        testOdrefresh();
    }

    @Test
    public void testOdrefreshSpeedProfile() throws Exception {
        getDevice().setProperty(SYSTEM_SERVER_COMPILER_FILTER_PROP_NAME, "speed-profile");
        testOdrefresh();
    }

    @Test
    public void testBootWithAndWithoutCompOS()
            throws DeviceNotAvailableException, InterruptedException {

        double[] bootWithCompOSTime = new double[ROUND_COUNT];
        double[] bootWithoutCompOSTime = new double[ROUND_COUNT];

        for (int round = 0; round < ROUND_COUNT; ++round) {

            // Boot time with compilation OS test.
            reInstallApex();
            compileStagedApex();
            long start = System.nanoTime();
            rebootAndWaitBootCompleted();
            long elapsedWithCompOS = System.nanoTime() - start;
            double elapsedSec = elapsedWithCompOS / NANOS_IN_SEC;
            bootWithCompOSTime[round] = elapsedSec;
            CLog.i("Boot time with compilation OS took " + elapsedSec + "s");

            // Boot time without compilation OS test.
            reInstallApex();
            start = System.nanoTime();
            rebootAndWaitBootCompleted();
            long elapsedWithoutCompOS = System.nanoTime() - start;
            elapsedSec = elapsedWithoutCompOS / NANOS_IN_SEC;
            bootWithoutCompOSTime[round] = elapsedSec;
            CLog.i("Boot time without compilation OS took " + elapsedSec + "s");

            assertWithMessage("Boot time with compilation OS is higher than without")
                .that(elapsedWithCompOS < elapsedWithoutCompOS).isTrue();
        }

        reportMetric("boot_time_with_compos", "s", bootWithCompOSTime);
        reportMetric("boot_time_without_compos", "s", bootWithoutCompOSTime);
    }

    private void reportMetric(String name, String unit, double[] values) {
        double sum = 0;
        double squareSum = 0;
        double min = Double.MAX_VALUE;
        double max = Double.MIN_VALUE;

        for (double val : values) {
            sum += val;
            squareSum += val * val;
            min = val < min ? val : min;
            max = val > max ? val : max;
        }

        double average = sum / values.length;
        double variance = squareSum / values.length - average * average;
        double stdev = Math.sqrt(variance);

        TestMetrics metrics = new TestMetrics();
        metrics.addTestMetric(METRIC_PREFIX + name + "_average_" + unit, Double.toString(average));
        metrics.addTestMetric(METRIC_PREFIX + name + "_min_" + unit, Double.toString(min));
        metrics.addTestMetric(METRIC_PREFIX + name + "_max_" + unit, Double.toString(max));
        metrics.addTestMetric(METRIC_PREFIX + name + "_stdev_" + unit, Double.toString(stdev));
    }

    private void waitForBootCompleted() throws InterruptedException, DeviceNotAvailableException {
        for (int i = 0; i < BOOT_COMPLETE_POLL_RETRY_COUNT; i++) {
            if (isBootCompleted()) {
                return;
            }
            Thread.sleep(BOOT_COMPLETE_POLL_INTERVAL);
        }
    }

    private boolean isBootCompleted() throws DeviceNotAvailableException {
        return BOOT_COMPLETED_VAL.equals(
                getDevice().executeShellCommand(BOOT_COMPLETED_PROP).trim());
    }

    private void rebootAndWaitBootCompleted()
            throws InterruptedException, DeviceNotAvailableException {
        getDevice().nonBlockingReboot();
        getDevice().waitForDeviceOnline();
        waitForBootCompleted();
    }

    private void compileStagedApex() throws DeviceNotAvailableException {
        CommandRunner android = new CommandRunner(getDevice());

        String result = android.run(
                COMPOSD_CMD_BIN + " staged-apex-compile");
        assertWithMessage("Failed to compile staged apex. Reason: " + result)
            .that(result.toLowerCase().contains("all ok")).isTrue();
    }

    private void reInstallApex() throws DeviceNotAvailableException {
        CommandRunner android = new CommandRunner(getDevice());

        String packagesOutput =
                android.run("pm list packages -f --apex-only");

        Pattern p = Pattern.compile(
                 "package:(.*)=(com(?:\\.google)?\\.android\\.art)$", Pattern.MULTILINE);
        Matcher m = p.matcher(packagesOutput);
        assertWithMessage("ART module not found. Packages are:\n" + packagesOutput)
            .that(m.find())
            .isTrue();

        String artApexPath = m.group(1);
        String artApexName = m.group(2);

        CommandResult result = android.runForResult(
                 "pm install --apex " + artApexPath);
        assertWithMessage("Failed to install APEX. Reason: " + result.toString())
             .that(result.getExitCode()).isEqualTo(0);
    }

    private void testOdrefresh() throws Exception {
        CommandRunner android = new CommandRunner(getDevice());

        // Prepare the groundtruth. The compilation on Android should finish successfully.
        {
            long start = System.currentTimeMillis();
            CommandResult result = runOdrefresh(android, "--force-compile");
            long elapsed = System.currentTimeMillis() - start;
            assertThat(result).exitCode().isEqualTo(COMPILATION_SUCCESS);
            CLog.i("Local compilation took " + elapsed + "ms");
        }

        // Save the expected checksum for the output directory.
        String expectedChecksumSnapshot = checksumDirectoryContentPartial(android,
                ODREFRESH_OUTPUT_DIR);

        // --check may delete the output.
        CommandResult result = runOdrefresh(android, "--check");
        assertThat(result).exitCode().isEqualTo(OKAY);

        // Expect the compilation in Compilation OS to finish successfully.
        {
            long start = System.currentTimeMillis();
            result =
                    android.runForResultWithTimeout(
                            ODREFRESH_TIMEOUT_MS, COMPOSD_CMD_BIN, "test-compile");
            long elapsed = System.currentTimeMillis() - start;
            assertThat(result).exitCode().isEqualTo(0);
            CLog.i("Comp OS compilation took " + elapsed + "ms");
        }
        killVmAndReconnectAdb();

        // Expect the BCC extracted from the BCC to be well-formed.
        assertVmBccIsValid();

        // Save the actual checksum for the output directory.
        String actualChecksumSnapshot = checksumDirectoryContentPartial(android,
                ODREFRESH_OUTPUT_DIR);

        // Expect the output of Comp OS to be the same as compiled on Android.
        assertThat(actualChecksumSnapshot).isEqualTo(expectedChecksumSnapshot);

        // Expect extra files generated by CompOS exist.
        android.run("test -f " + ODREFRESH_OUTPUT_DIR + "/compos.info");
        android.run("test -f " + ODREFRESH_OUTPUT_DIR + "/compos.info.signature");

        // Expect the CompOS signature to be valid
        android.run(COMPOS_VERIFY_BIN + " --debug --instance test");
    }

    private void assertVmBccIsValid() throws Exception {
        File bcc_file = getDevice().pullFile(COMPOS_APEXDATA_DIR + "/test/bcc");
        assertThat(bcc_file).isNotNull();

        // Add the BCC to test artifacts, in case it is ill-formed or otherwise interesting.
        mTestLogs.addTestLog(bcc_file.getPath(), LogDataType.UNKNOWN,
                new FileInputStreamSource(bcc_file));

        // Find the validator binary - note that it's specified as a dependency in our Android.bp.
        File validator = getTestInformation().getDependencyFile("bcc_validator", /*targetFirst=*/
                false);

        CommandResult result = new RunUtil().runTimedCmd(10000,
                validator.getAbsolutePath(), "verify-chain", bcc_file.getAbsolutePath());
        assertWithMessage("bcc_validator failed").about(command_results())
                .that(result).isSuccess();
    }

    private CommandResult runOdrefresh(CommandRunner android, String command) throws Exception {
        return android.runForResultWithTimeout(
                ODREFRESH_TIMEOUT_MS,
                ODREFRESH_BIN,
                "--dalvik-cache=" + TEST_ARTIFACTS_DIR,
                command);
    }

    private void killVmAndReconnectAdb() throws Exception {
        CommandRunner android = new CommandRunner(getDevice());

        android.tryRun("killall", "crosvm");
        android.tryRun("stop", "virtualizationservice");

        // Delete stale data
        android.tryRun("rm", "-rf", "/data/misc/virtualizationservice/*");
    }

    private String checksumDirectoryContentPartial(CommandRunner runner, String path)
            throws Exception {
        // Sort by filename (second column) to make comparison easier. Filter out compos.info and
        // compos.info.signature since it's only generated by CompOS.
        // TODO(b/211458160): Remove cache-info.xml once we can plumb timestamp and isFactory of
        // APEXes to the VM.
        return runner.run("cd " + path + "; find -type f -exec sha256sum {} \\;"
                + "| grep -v cache-info.xml | grep -v compos.info"
                + "| sort -k2");
    }
}
